server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: jig123
    password: root

  # mustache를 의존하겠다고 설정해두면 기본으로 경로가 아래와 같이 prefix, suffix가 설정된다.
  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .mustache

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  #참고 - https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: 값 필요
            client-secret: 값 필요
            scope: # scope("openid", "profile", "email", "address", "phone")
              - email
              - profile

          # "https://developers.facebook.com/docs/facebook-login/web#--------"에서 facebook scope 확인
          facebook:
            client-id: 값 필요
            client-secret: 값 필요
            scope:
              - email
              - public_profile

          # 네이버는 OAuth2.0 공식 지원대상이 아니라서 client-name, authorization-grant-type, redirect-uri, provider 설정이 필요하다.
          # 요청주소도 다르고, 응답 데이터도 다르기 때문이다.
          naver:
            client-id: 값 필요
            client-secret: 값 필요
            scope:
              - name
              - email
              # - profile_image
            client-name: Naver # 클라이언트 네임은 구글 페이스북도 대문자로 시작하더라.
            authorization-grant-type: authorization_code # 인증 방식은 뭘 사용하는지.
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 네이버 로그인 인증 요청
            token-uri: https://nid.naver.com/oauth2.0/token # 접근 토큰 발급 요청
            user-info-uri: https://openapi.naver.com/v1/nid/me # 접근 토큰을 이용하여 프로필 API 호출하기 - 프로필 정보 조회
            user-name-attribute: response # 네이버가 회원정보를 json 데이터인 response라는 키값으로 리턴해줌.